### ISSUE TITLE
Some files could not be processed

### ISSUE THREAD

**Issue by SvenC56** [jemishgopani/wdio-mochawesome-reporter#47] opened 2019-08-16 07:27 UTC
I get a weird error:

``` bash
 marge results/mochawesome/wdio-ma-merged.json --reportTitle 'My Project Results'
```

```
✘ Some files could not be processed:
results/mochawesome/wdio-ma-merged.json
  Invalid value "success" supplied to /stats/passPercentClass: Nil
  Invalid value "danger" supplied to /stats/pendingPercentClass: Nil
  Invalid value undefined supplied to /results: Array<Suite>
  Invalid value {
  "title": "",
  "suites": [
    {
      "title": "webdriver.io page (chrome.76_0_3809_100.windowsnt)",
      "suites": [],
      "tests": [
        {
          "title": "should have the right title",
          "fullTitle": "should have the right title",
          "timedOut": false,
          "duration": 1649,
          "speed": "fast",
          "pass": true,
          "fail": false,
          "pending": false,
          "code": "",
          "isRoot": false,
          "uuid": "d4f60518-2c07-403e-85dd-3efa9766cccf",
          "parentUUID": "ec976a94-694d-40fb-a494-12ef1e4628d2",
          "skipped": false,
          "isHook": false,
          "context": "[{\"title\":\"Session Id\",\"value\":\"1170aca5c22554247c39c5fffd9ff0ba\"}]",
          "state": "passed",
          "err": {}
        }
      ],
      "pending": [],
      "root": false,
      "fullFile": "",
      "file": "",
      "passes": [
        "d4f60518-2c07-403e-85dd-3efa9766cccf"
      ],
      "failures": [],
      "skipped": [],
      "duration": 1667,
      "_timeout": 0,
      "uuid": "ec976a94-694d-40fb-a494-12ef1e4628d2",
      "beforeHooks": [],
      "afterHooks": []
    }
  ],
  "tests": [],
  "pending": [],
  "root": true,
  "fullFile": "",
  "file": "",
  "passes": [],
  "failures": [],
  "skipped": [],
  "duration": 0,
  "_timeout": 0,
  "uuid": "4d07d487-c56c-4c1f-b722-f05bc1dcb55b",
  "beforeHooks": [],
  "afterHooks": []
} supplied to /suites: Nil
  Invalid value 2019 supplied to /copyrightYear: Nil
```

JSON looks like: 
``` json
{
    "stats": {
        "suites": 1,
        "tests": 1,
        "passes": 1,
        "pending": 0,
        "failures": 0,
        "start": "2019-08-16T07:24:32.060Z",
        "end": "2019-08-16T07:24:36.799Z",
        "duration": 4739,
        "testsRegistered": 1,
        "passPercent": 100,
        "pendingPercent": 0,
        "other": 0,
        "hasOther": false,
        "skipped": 0,
        "hasSkipped": false,
        "passPercentClass": "success",
        "pendingPercentClass": "danger"
    },
    "suites": {
        "title": "",
        "suites": [
            {
                "title": "webdriver.io page (chrome.76_0_3809_100.windowsnt)",
                "suites": [],
                "tests": [
                    {
                        "title": "should have the right title",
                        "fullTitle": "should have the right title",
                        "timedOut": false,
                        "duration": 1649,
                        "speed": "fast",
                        "pass": true,
                        "fail": false,
                        "pending": false,
                        "code": "",
                        "isRoot": false,
                        "uuid": "d4f60518-2c07-403e-85dd-3efa9766cccf",
                        "parentUUID": "ec976a94-694d-40fb-a494-12ef1e4628d2",
                        "skipped": false,
                        "isHook": false,
                        "context": "[{\"title\":\"Session Id\",\"value\":\"1170aca5c22554247c39c5fffd9ff0ba\"}]",
                        "state": "passed",
                        "err": {}
                    }
                ],
                "pending": [],
                "root": false,
                "fullFile": "",
                "file": "",
                "passes": ["d4f60518-2c07-403e-85dd-3efa9766cccf"],
                "failures": [],
                "skipped": [],
                "duration": 1667,
                "_timeout": 0,
                "uuid": "ec976a94-694d-40fb-a494-12ef1e4628d2",
                "beforeHooks": [],
                "afterHooks": []
            }
        ],
        "tests": [],
        "pending": [],
        "root": true,
        "fullFile": "",
        "file": "",
        "passes": [],
        "failures": [],
        "skipped": [],
        "duration": 0,
        "_timeout": 0,
        "uuid": "4d07d487-c56c-4c1f-b722-f05bc1dcb55b",
        "beforeHooks": [],
        "afterHooks": []
    },
    "copyrightYear": 2019
}
```

Versions: 
* "mochawesome-report-generator": "^3.1.5"
* "wdio-mochawesome-reporter": "^3.2.0"
* Latest WDIO 5.12.1

``` javascript
reporters: [
        'dot',
        ['allure', { outputDir: './results/allure' }],
        [
            'mochawesome',
            {
                outputDir: './results/mochawesome',
                outputFileFormat: function(opts) {
                    const now = +new Date()
                    return `results-${now}.json`
                },
            },
        ],
    ],

onComplete: function(exitCode, config, capabilities, results) {
        const mergeResults = require('wdio-mochawesome-reporter/mergeResults')
        mergeResults('./results/mochawesome', 'results-*')
    },
```

Is something missing?

**Comment by fijijavis** [comment] 2019-08-16 10:32
@svenC56 Could you provide a minimal test that reproduces the issue?

**Comment by SvenC56** [comment] 2019-08-16 11:46
Hi @fijijavis I uploaded a small Repo to reproduce the issue.

https://github.com/SvenC56/webdriver-io-boilerplate-error

Thank you.

**Comment by maeriens** [comment] 2019-09-15 02:07
@SvenC56 the issue is that you are using `mochawesome-report-generator@4`, which changed the structure of the file. Downgrade to v3 to have it working again.

**Comment by apyarun** [comment] 2020-01-23 09:22
I'm also getting the same issue:

**Comment by MehranShafqat** [comment] 2020-03-04 07:31
Having same issue even downgrade to 3.1.5 :( not working

✘ Some files could not be processed:
cypress/reports/mochawesome.json
  Unexpected token � in JSON at position 0

**Comment by cristiangonzalezteracode** [comment] 2021-06-07 13:16
@MehranShafqat @apyarun @SvenC56 were you able to figure it out? I tried downgrading to v3 and it did not work

**Comment by bkaleFB** [comment] 2021-10-01 13:31
It apparently works well with mochawesome-report-generator @2.3.2 but that doesnt work with my tests either. Same error.

**Comment by jjii123** [comment] 2022-05-22 04:11
Some files could not be processed:
./build/logs/mochawesome/results/wdio-ma-merged.json
  Invalid value "success" supplied to /stats/passPercentClass: Nil
  Invalid value "danger" supplied to /stats/pendingPercentClass: Nil
  Invalid value undefined supplied to /results: Array<Suite>
  Invalid value {
  "title": "",
  "suites": [
  The HTML files is not getting generated for the failed test scenarios. I can generate the HTML report for the passed scenarios. Please advise, I have added the merge command on the onComplete hooks.
        const mergeResults = require('wdio-mochawesome-reporter/mergeResults')
        mergeResults('./results/mochawesome', 'results-*')
Any suggestion?

**Comment by Manuel-Suarez-Abascal** [comment] 2022-12-02 20:54
Are there any updates on this issue? I'm having a similar issue.

**Closed** 2024-07-14 16:52 UTC
